### ISSUE TITLE
additional libraries are requires not listed in the install guide

### ISSUE THREAD

**Issue by gazzat5** [gromeck/BLE-Scanner#17]
hi there, i was trying to use this in the new arduino ide 2.0 rc and it wouldn't compile, with missing libraries TimeLib.h and util.h.
Not sure if this problem is limited to the 2.0 ide or not

**Comment by gromeck** [comment]
Sorry for my late reply.

> i was trying to use this in the new arduino ide 2.0 rc

I am still on 1.8.x and it works there.

> and it wouldn't compile, with missing libraries TimeLib.h

this is not a lib but an include coming from the Time library. Ensure that it is installed. I also updated the README.md

> and util.h.

this is part of the project, maybe a consequence from the above, or an ide 2.0 issue.

**Comment by gromeck** [comment]
Will close the issue because of no reply to the comment https://github.com/gromeck/BLE-Scanner/issues/17#issuecomment-1165531673
