### ISSUE TITLE
Web Frontend Access

### ISSUE THREAD

**Issue by schmeckm** [gromeck/BLE-Scanner#18]
Hi ALL,
Can someone tell me how I can access the webfrontend to see the RSSI Values by beacons?
If I call the IP Addresse in the browser the system request the 
<username> and 
<password>.

What is the username or passsword?  

BR, Markus

**Comment by gromeck** [comment]
By default, there is no password set.
If the device comes up the first time, it will not find a valid configuration stored in the EEPROM. This will bring up the device in configuration mode.
I assume that you configured a password by accident.
You can force a configuration change by changing the CONFIG_MAGIC once, flash it and restart the device.
The username is (as described in the configuration dialog) "admin".

**Comment by gromeck** [comment]
Again, if you are asked for a username and password, you set a password in the configuration mode before -- maybe by accident.
I already described how to enforce the configuration mode once more, so that you can reconfigure the deice (without password).

**Comment by gromeck** [comment]
Will close the issue because of no reply to https://github.com/gromeck/BLE-Scanner/issues/18#issuecomment-1182788537
