### ISSUE TITLE
include Name in every output on mqtt

### ISSUE THREAD

**Issue by RogierQ** [gromeck/BLE-Scanner#19]
I have a project were i use the names of the ble instead of the mac.
Is it possible to include the name in every output scan?
If so how can i do that?

**Comment by gromeck** [comment]
Sorry for the late reply.
What do you mean with output scan?
Are you requesting the MQTT publishing of the device name? If so, it is published, but only if available and revealed by the BLE device.

**Comment by gromeck** [comment]
will be closed as there was no further response
