### ISSUE TITLE
Question about documentation

### ISSUE THREAD

**Issue by khakieconomics** [gromeck/BLE-Scanner#21]
A very basic question which wasn't obvious to me from the Readme: 

I have managed to connect to my Wifi and restarted the device, but I don't know how to connect to the service. Any help on this would be greatly appreciated!

**Comment by gromeck** [comment]
Ok, if you could configure your device, it restarted after the configuration and it will get (hopefully) an automatic IP address by your DHCP service (normally your router). So, you should check there which IP address the scanner has.
If you know the IP address, you open a browser with the URL http://<ipaddr>/ -- that's it.

**Comment by khakieconomics** [comment]
Thanks! This software is an extremely useful contribution. I appreciate it. 

Still having some small issues. When it connects to the local Wifi, the Serial Monitor prints:

```
00:00:00 01.01.1970: WIFI: my MAC address is 08:B6:1F:81:04:C4
00:00:00 01.01.1970: WIFI: waiting to connect to [Network name]
00:00:05 01.01.1970: WIFI: connected to [Network name] with local IP address 10.175.241.29
00:00:05 01.01.1970: HTTP: setting up HTTP server
00:00:05 01.01.1970: HTTP: server started
```
I have also verified with `arp -a` that `10.175.241.29` is on my network. Yet I cannot connect to it through a browser. 
One error being printed to the Serial Monitor is: 

```
00:08:43 01.01.1970: MQTT: reconnecting :@fhem.site:1883 width clientID BLEscanner ...
00:08:43 01.01.1970: MQTT: connection failed, rc=-2 -- trying again in 10 seconds
00:08:43 01.01.1970: MQTT: connect_status=0
```

I just followed your screenshots literally, but I suspect "fhem.site" is not what I'm meant to write here. 

Any help greatly appreciated.

**Comment by gromeck** [comment]
Yes, sorry, `fhem.site` is an example in my environment.
Nevertheless, you should be able to connect to the web service, in your case you should try `http://10.175.241.29/` even if there is no MQTT setup.
Ensure that you use HTTP -- not HTTPS -- to connect.
Does the device respond to a ping?
Does your router allow that WiFi devices communicate to each other? (its a security feature most of the routers have)

**Comment by gromeck** [comment]
will close this issue as there was no response
